### PR TITLE
Fix MAL mode 0 episode bug

### PR DESCRIPTION
**Pull request by Zulltar-of-Xanduin**
Fixed a bug that was causing MAL mode not to display an anime if no episodes had been watched and MAL didn't list the total number of episodes yet (i.e. for some anime that are still airing)

### CODE REVIEW

**Comment by Zulltar-of-Xanduin** [comment]
Shows with 0 eps listed on MAL display now, but I forgot to check whether they actually play when selected. It currently let's you pick the show, but returns "Nothing to watch." I think I know why that's happening; will look into it.

**Comment by Zulltar-of-Xanduin** [comment]
I'm not sure how to fix this problem elegantly. For the moment I just added a check to see if MAL lists the total number of episodes, and if it doesn't, check for the next episode anyway. This only allows us to check for 1 episode at a time though, which is not ideal.

**Comment by sdaqo** [comment]
So if MAL does not list episode the api returns 0?

just an idea: how about if the api returns 0, we just check until the first episode not found in the provider and break when the first episode is skipped?

**Comment by sdaqo** [comment]
here
```
                        except ValueError:
                            s.write(
                                f"> Episode {ep} not found in provider, skipping..."
                            )
```

**Comment by Zulltar-of-Xanduin** [comment]
> and just assume a large number so the loop runs "forever"

Okay, yeah that makes sense. I was trying to figure out how to make it work every time for every show, not in terms of this being the fringe case that it is. I'll get on that.


> So if MAL does not list episode the api returns 0?

Yeah it's rare but there seem to be one or two shows in a season that MAL doesn't list the episode count until it's done airing.
"Ao no Miburo" is the one I've noticed doing it this season.

**Comment by Zulltar-of-Xanduin** [comment]
Seems to work for me now. I'll do some more testing just in case, but I think it's all good.

**Comment by sdaqo** [comment]
I think we can assume an even bigger number considering shows like one piece exist, something like 9999, I know ridiculous, but one piece has like 1000 episodes... and it's still airing.

**Comment by Zulltar-of-Xanduin** [comment]
Yeah I was thinking MAL would probably always know how many episodes of one piece there are, but I guess there really isn't a reason not to do it that way lol

**Review by sdaqo — APPROVED** [review]

**Pull request merged**
