### PR TITLE
feature: animetoast provider

### PR DESCRIPTION
**Pull request by schmanimus**
Adds Animetoast as a provider, which is a German site and would allow to watch anime in German dub and sub.

Not finished completely but is in a working state and ready for testing.
**Note:** I don't have a MAL account, so I can't say how good that works.

### TODO:
- [x] get actual page count when searching
- [ ] ~~update availability.md - should I increase the version number and if yes in which way?~~

### CODE REVIEW

**Comment by sdaqo** [comment]
Very cool, I also speak German, didn't know of this site! I will test/review when you are done. If you need any help, do ask!

**Comment by sdaqo** [comment]
About the availability docs: I will do it when I release the new version, don't bother. There is space for a little note though, so if there is something important , just tell me and I will put it in.

**Comment by schmanimus** [comment]
Okay, thanks!

**Comment by sdaqo** [comment]
This seems to be working just fine, is there a reason why it's still a draft?

**Comment by schmanimus** [comment]
Hi, sorry for the delay.
I fixed a small issue and in theory it should be working quite nicely now.

After pushing I thought about marking it as ready for review now.
But after thinking about it and looking up how other tools like yt-dlp do it and that they removed support for many sites, I made the decision that I would like to close the PR instead.

I can't stop you from adding it anyways, but please don't use my commits directly.

**Comment by sdaqo** [comment]
that's fine, no worries

**Pull request closed without merging**
