### PR TITLE
More browser compatibility

### PR DESCRIPTION
**Pull request by Dankni95**
Hi again,

I'm not sure if you want to implement something like this, but this makes it possible to use chrome and chromium for webdrivers.

What do you think?

Tested on Linux and Windows, as i have no mac there is no implementation for it, so it defaults to Firefox.
Daniel

### CODE REVIEW

**Comment by sdaqo** [comment]
Hi, thanks for another contribution, I never thought this little project would get so "big". As for the PR, looks sweet. Regarding macos I think defaulting to firefox is a good idea since I didn't found a option for the safari webdriver in the `webdriver-manager` module. Thanks again.

**Comment by Dankni95** [comment]
No problem, it's perfect project to learn Github collaboration and Python for me :smile:

**Comment by sdaqo** [comment]
This is the exact same thing I'm doing. I thought, I like anime: yes, I want to learn Python and programming in general: yes, the perfect project.

**Comment by Dankni95** [comment]
Hey @sdaqo 
I used your tool to create an extension for ulauncher:
https://github.com/Dankni95/ulauncher-anime

What do you think?

**Comment by sdaqo** [comment]
Oh that looks amazing, should I add a link in my readme?

**Comment by Dankni95** [comment]
Thanks! That would be great :smile: 
Also i would highly appreciate if you could try to set up the extension and tell me if everything works!

If you have time for it, that is!

**Comment by sdaqo** [comment]
Hi, I tried your tool. Some things:
-  Anime searching works fine adn withouyt problems.
- when typing `ani h` I just get  this: https://imgur.com/a/TBRA9hp (sorry for bad quality) I dont know if I'm just dumb or if it really is a bug.
-  You might want to change the quality option 780 to 720 because 780p isnt an option on gogoanime

I tested this on linux arch with i3 wm

**Comment by Dankni95** [comment]
Wow, great catch.. i guess i forgot to test if everything works from scratch when creating history

Added better error message, as what you were getting was "error" array looped for every letter lol 
Hopefully everything works now!

Thank you for testing, highly appreciate it!
If you could see if everything works now, that would be great, easy to miss stuff coding

**Comment by sdaqo** [comment]
Sorry for the late replay. I tried again and everything works fine now.

**Comment by Dankni95** [comment]
> Sorry for the late replay. I tried again and everything works fine now.

No problem, thank you for your time!

If you ever need any help, im here :+1:

**Pull request merged**
