### PR TITLE
Add pycrypto to requirements.txt because it is a dependency 

### PR DESCRIPTION
**Pull request by Dabbing-Guy**
I tried running `anipy-cli -d` and it had the following error message: 
```
Traceback (most recent call last):
  File "/usr/local/bin/anipy-cli", line 4, in <module>
    from anipy_cli import cli
  File "/home/michael/Projects/anipy-cli/anipy_cli/cli.py", line 4, in <module>
    from .url_handler import epHandler, videourl
  File "/home/michael/Projects/anipy-cli/anipy_cli/url_handler.py", line 10, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
```
So, I looked up "Crypto python module" and found `pycrypto` on PyPI. I installed it with pip, and it worked. Since it was not in `requirements.txt`, I added and made this pull request.

### CODE REVIEW

**Comment by Dabbing-Guy** [comment]
Might not be the correct crypto module. After selecting an episode to watch, I get this error message: 
```
Traceback (most recent call last):
  File "/usr/local/bin/anipy-cli", line 9, in <module>
    cli.main()
  File "/home/michael/Projects/anipy-cli/anipy_cli/cli.py", line 262, in main
    default_cli(args.quality)
  File "/home/michael/Projects/anipy-cli/anipy_cli/cli.py", line 29, in default_cli
    url_class.stream_url()
  File "/home/michael/Projects/anipy-cli/anipy_cli/url_handler.py", line 203, in stream_url
    id = self.aes_decrypt(crypto)
  File "/home/michael/Projects/anipy-cli/anipy_cli/url_handler.py", line 183, in aes_decrypt
    return AES.new(self.key, self.mode, iv=self.iv).decrypt(
  File "/home/michael/.local/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/home/michael/.local/lib/python3.10/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/home/michael/.local/lib/python3.10/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```

I don't know if this is from a problem with the program, a bug in `pycrypto`, or if this is just the wrong crypto module.

**Comment by sdaqo** [comment]
Hey, I think it's called pycryptodome. Could you also add this, with tqdm which I forgot to setup.py in the install requirements? Thanks

**Comment by sdaqo** [comment]
Actually, nevermind install pycryptodomex, it does not break when pycrypto is installed as well, I commited something for it to work

**Comment by Dabbing-Guy** [comment]
Done.

**Pull request merged**
