### PR TITLE
Fixed Multi Threaded m3u8 Download and added check if file exists before DL

### PR DESCRIPTION
**Pull request by dymattic**
made quite some changes to the multi threaded downloading of m3u8 playlists.
Heavily inspired by [this](https://github.com/ChenTanyi/m3u8-downloader) project.

Requires ffmpeg for mergin downloaded parts now.

### CODE REVIEW

**Comment by dymattic** [comment]
Downloaded files without audio, needs more work

**Comment by dymattic** [comment]
OK Multi threaded m3u8 DLs work with audio and correct qualit now :D

**Comment by sdaqo** [comment]
@dymattic can we avoid using ffmpeg to merge the files, since it is an external program? I guess you used it for merging audio and video? How about we try someting like [this](https://www.geeksforgeeks.org/moviepy-assigning-audio-clip-to-video-file/) its a python libary not using external programs.

**Comment by dymattic** [comment]
> @dymattic can we avoid using ffmpeg to merge the files, since it is an external program? I guess you used it for merging audio and video? How about we try someting like [this](https://www.geeksforgeeks.org/moviepy-assigning-audio-clip-to-video-file/) its a python libary not using external programs.

Yea you're right about that.
Isn't the ffmpeg method I use also a python library? Or is it just a wrapper for ffmpeg?

**Comment by sdaqo** [comment]
> yea you're right about that.
Isn't the ffmpeg method I use also a python library? Or is it just a wrapper for ffmpeg?

Its just a wrapper and executes a process. 
And the libary what I pointed out also uses ffmpeg, I got that wrong, but it installs it automatically, this is what it says on there page: 
> MoviePy depends on the software FFMPEG for video reading and writing. You don’t need to worry about that, as FFMPEG should be automatically downloaded/installed by ImageIO during your first use of MoviePy (it takes a few seconds). If you want to use a specific version of FFMPEG, you can set the FFMPEG_BINARY environment variable See moviepy/config_defaults.py for details.

I think we should prefer this methode over using just a wrapper.

**Comment by dymattic** [comment]
> > yea you're right about that.
> > Isn't the ffmpeg method I use also a python library? Or is it just a wrapper for ffmpeg?
> 
> Its just a wrapper and executes a process. And the libary what I pointed out also uses ffmpeg, I got that wrong, but it installs it automatically, this is what it says on their page:
> 
> > MoviePy depends on the software FFMPEG for video reading and writing. You don’t need to worry about that, as FFMPEG should be automatically downloaded/installed by ImageIO during your first use of MoviePy (it takes a few seconds). If you want to use a specific version of FFMPEG, you can set the FFMPEG_BINARY environment variable See moviepy/config_defaults.py for details.
> 
> I think we should prefer this methode over using the ffmpeg lib.

You are right, switched to using ffmpeg via moviepy now :+1:

**Comment by sdaqo** [comment]
Ok, nice! Thanks for the PR.

**Pull request merged**
